name: TruffleHog Secret Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run TruffleHog Secret Scan
      uses: trufflesecurity/trufflehog@v3
      with:
        path: .
        extra_args: --fail --only-verified
