name: TruffleHog Git + Filesystem Secret Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  trufflehog-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Scan Git history for secrets
        run: |
          echo "Scanning Git history..."
          docker run --rm \
            -v "$PWD:/repo" \
            ghcr.io/trufflesecurity/trufflehog:latest \
            git /repo --only-verified --fail || true

      - name: Scan working directory (filesystem) for secrets
        run: |
          echo "Scanning working directory..."
          docker run --rm \
            -v "$PWD:/repo" \
            ghcr.io/trufflesecurity/trufflehog:latest \
            filesystem /repo --only-verified --fail || true
